parameters:
#    codemasters_jobeet.example.class: Codemasters\Bundle\JobeetBundle\Example

services:
#    codemasters_jobeet.example:
#        class: %codemasters_jobeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
